# Config file for automatic testing at travis-ci.org

language: python
dist: xenial  # required for Python >= 3.7
python:
  - "3.7"
  - "3.6"
  - "3.5"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

after_success:
  - pip install codecov
  - codecov -e TOX_ENV
